#PBS -N 07
#PBS -l nodes=1:ppn=1
#PBS -l pmem=4gb
#PBS -l walltime=1:00:00
#PBS -q hive
#PBS -j oe
#PBS -o /storage/home/hhive1/cchen641/scratch/icecube/job_pbs_out/out/07.out
#PBS -t 1-23%400
cd /storage/home/hhive1/cchen641/icecube/greco_grb/scripts
icpy3
params=`sed -n "${PBS_ARRAYID} p" hive_sub/07.txt`
paramsArray=($params)
arg0=${paramsArray[0]}
arg1=${paramsArray[1]}
python 07_effective_trial_factor.py --grb_idx_start $arg0 --grb_idx_end $arg1 