#PBS -N 08
#PBS -l nodes=1:ppn=4
#PBS -l pmem=4gb
#PBS -l walltime=24:00:00
#PBS -q hive
#PBS -j oe
#PBS -o /storage/home/hhive1/cchen641/scratch/icecube/job_pbs_out/out/08.out
#PBS -t 1-4%400
cd /storage/home/hhive1/cchen641/icecube/greco_grb/scripts
icpy3
params=`sed -n "${PBS_ARRAYID} p" hive_sub/08.txt`
paramsArray=($params)
arg0=${paramsArray[0]}
arg1=${paramsArray[1]}
python 08_save_multiple_run_post_p_for_null_binomial.py --num_run $arg0 