#PBS -N 10
#PBS -l nodes=1:ppn=1
#PBS -l pmem=30gb
#PBS -l walltime=2:00:00
#PBS -q hive
#PBS -j oe
#PBS -o /storage/home/hhive1/cchen641/scratch/icecube/job_pbs_out/out/10.out
#PBS -t 1-3%400
cd /storage/home/hhive1/cchen641/icecube/greco_grb/scripts
icpy3
params=`sed -n "${PBS_ARRAYID} p" hive_sub/10.txt`
paramsArray=($params)
arg0=${paramsArray[0]}
python 10_get_permuted_null_binomial_test_results.py --seed $arg0 