#PBS -N hivePythonExample       # job name
#PBS -l nodes=1:ppn=4           # number of nodes and cores per node required
#PBS -l pmem=1gb                # memory per core
#PBS -l walltime=15:00          # duration of the job (ex: 15 min)
#PBS -q hive                # queue name (where job is submitted)
#PBS -j oe                      # combine output and error messages into 1 file
#PBS -o /storage/home/hhive1/cchen641/scratch/icecube/job_log_out_err/hivePythonExample.out   # output file name

cd $PBS_O_WORKDIR 

module load anaconda3/2019.07

python test.py

